site_name: "SC Crawler"
repo_url: https://github.com/spareCores/sc-crawler/
edit_uri: blob/main/docs/

extra:
  homepage: https://sparecores.com
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/spareCores
    - icon: custom/dbdocs
      link: https://dbdocs.io/spare-cores/sc-crawler
    - icon: fontawesome/solid/database
      link: https://dbhub.io/SpareCores
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/SpareCores
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/SpareCores
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/SpareCores/

nav:
  - index.md
  - add_vendor.md
  - Reference: reference/
  - Changelog: CHANGELOG.md

theme:
  name: "material"
  custom_dir: overrides
  logo: logo-horizontal.png
  favicon: logo-128x128.png
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.edit
    - content.code.copy
    - content.code.annotate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - toc.integrate
    - search.suggest
    - navigation.footer
    - optimize

extra_css:
  - stylesheets/extra.css
  - asciinema-player/asciinema-player.css

extra_javascript:
  - asciinema-player/asciinema-player.min.js

plugins:
- search
- autorefs
- gen-files:
    scripts:
    - scripts/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        - https://rich.readthedocs.io/en/stable/objects.inv
        - https://docs.pydantic.dev/latest/objects.inv
        - https://docs.sqlalchemy.org/en/20/objects.inv
        # TODO objects.inv for SQLModel
        options:
          show_source: true
          show_signature: true
          separate_signature: true
          show_root_heading: true
          show_signature_annotations: false
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          signature_crossrefs: true
          members_order: source
          group_by_category: false
          summary: true
          extensions:
          - scripts/dynamic_docstrings.py:DynamicDocstrings
# - social:
#     enabled: !ENV [CI, false]

markdown_extensions:
  - toc:
      permalink: "#"
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
