site_name: "Spare Cores Crawler"
repo_url: https://github.com/spareCores/sc-crawler/
edit_uri: blob/main/docs/

theme:
  name: "material"
  logo: logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.edit

plugins:
- search
- autorefs
- gen-files:
    scripts:
    - scripts/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        - https://rich.readthedocs.io/en/stable/objects.inv
        - https://docs.pydantic.dev/latest/objects.inv
        # TODO objects.inv for SQLModel
        options:
          show_source: true
          show_signature: true
          separate_signature: true
          show_root_heading: true
          show_signature_annotations: false
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          signature_crossrefs: true
          summary: true
          extensions:
          - scripts/dynamic_docstrings.py:DynamicDocstrings

markdown_extensions:
  - toc:
      permalink: "#"
